services:
  demo-app:
    image: centralserver:latest   # 미리 빌드한 Spring Boot jar를 사용
    build:
      context: ./actions-runner/deploy
      dockerfile: Dockerfile
    container_name: centralserver
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default


