version: '3.9'

services:
  demo-app:
    image: centralserver:latest   # 미리 빌드한 Spring Boot jar를 사용
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centralserver
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    # MongoDB는 아직 연결하지 않으므로 의존성 없음

# 나중에 MongoDB를 추가할 경우 이렇게 추가 가능
#  mongodb:
#    image: mongo:latest
#    container_name: central-mongo
#    environment:
#      MONGO_INITDB_DATABASE: mydatabase
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: secret
#    ports:
#      - "27017:27017"
#    networks:
#      - demo-network
#
#networks:
#  demo-network:
#    driver: bridge

