services:
  demo-app:
    image: centralserver:latest   # 미리 빌드한 Spring Boot jar를 사용
    build:
      context: .
      dockerfile: Dockerfile
    container_name: davidjk522/centralserver:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default


